/**
 * Vercel serverless function — generates a visual using Napkin.ai API.
 * Replaces the previous Claude-based chart generation.
 */

const NAPKIN_BASE = 'https://api.napkin.ai'
const DEFAULT_STYLE = 'CDQPRVVJCSTPRBBCD5Q6AWR' // Vibrant Strokes

export default async function handler(req, res) {
  // CORS headers
  res.setHeader('Access-Control-Allow-Origin', '*')
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS')
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type')

  if (req.method === 'OPTIONS') return res.status(200).end()
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' })

  const apiKey = process.env.NAPKIN_API_KEY
  if (!apiKey) return res.status(500).json({ error: 'NAPKIN_API_KEY not configured on server' })

  const { text, forcedType } = req.body || {}
  if (!text || typeof text !== 'string' || !text.trim()) {
    return res.status(400).json({ error: 'Text input is required' })
  }

  try {
    // Build request body
    const body = {
      format: 'svg',
      content: '[IMPORTANT: All text in the visual MUST be in English.]\n\n' + text.trim(),
      style_id: DEFAULT_STYLE,
      number_of_visuals: 1,
    }

    // Map forcedType to visual_query if provided
    if (forcedType) {
      body.visual_query = forcedType
    }

    // Step 1: Create visual request
    const createRes = await fetch(`${NAPKIN_BASE}/v1/visual`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${apiKey}`,
      },
      body: JSON.stringify(body),
    })

    if (!createRes.ok) {
      const errData = await createRes.json().catch(() => ({}))
      const msg = errData.message || errData.error || `Napkin API error (${createRes.status})`
      return res.status(502).json({ error: msg })
    }

    const createData = await createRes.json()
    const requestId = createData.id

    if (!requestId) {
      return res.status(502).json({ error: 'No request ID returned from Napkin API' })
    }

    // Step 2: Poll for completion with exponential backoff
    let delay = 2000
    const maxWait = 45000
    let elapsed = 0
    let statusData = null

    while (elapsed < maxWait) {
      await new Promise(r => setTimeout(r, delay))
      elapsed += delay

      const statusRes = await fetch(`${NAPKIN_BASE}/v1/visual/${requestId}/status`, {
        headers: { 'Authorization': `Bearer ${apiKey}` },
      })

      if (statusRes.status === 410) {
        return res.status(502).json({ error: 'Napkin request expired' })
      }

      if (!statusRes.ok) {
        // Retry on transient errors
        delay = Math.min(delay * 2, 8000)
        continue
      }

      statusData = await statusRes.json()

      if (statusData.status === 'completed') break
      if (statusData.status === 'failed') {
        return res.status(502).json({ error: 'Napkin visual generation failed' })
      }

      // Still pending, increase delay
      delay = Math.min(delay * 2, 8000)
    }

    if (!statusData || statusData.status !== 'completed') {
      return res.status(504).json({ error: 'Napkin visual generation timed out' })
    }

    const files = statusData.generated_files || []
    if (files.length === 0) {
      return res.status(502).json({ error: 'No files generated by Napkin' })
    }

    // Step 3: Download the SVG file
    const fileUrl = files[0].url
    const fileRes = await fetch(fileUrl, {
      headers: { 'Authorization': `Bearer ${apiKey}` },
    })

    if (!fileRes.ok) {
      return res.status(502).json({ error: 'Failed to download generated visual' })
    }

    const svgBuffer = await fileRes.arrayBuffer()
    const base64 = Buffer.from(svgBuffer).toString('base64')
    const imageUrl = `data:image/svg+xml;base64,${base64}`

    return res.status(200).json({
      type: 'napkin-image',
      title: 'Generated Visual',
      imageUrl,
    })
  } catch (err) {
    return res.status(500).json({
      error: `Failed to generate visual: ${err.message}`,
    })
  }
}
